---
name: Unit Tests
on:
  push:    
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '**.go'
      - 'vendor/**'
      - '.github/workflows/**'

jobs:
  build:
    strategy:
      matrix:
        go-version:
          - "1.14"
          - "1.15"
          - "1.16"
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - run: bash scripts/gogetcookie.sh
      - run: make test

